<?php

namespace backend\controllers;

use common\models\Department;
use common\models\Partner;
use common\models\PropertyDetails;
use common\models\PropertyDetailsQuery;
use common\models\User;
use common\models\Vindulosning;
use Yii;
use yii\data\ActiveDataProvider;
use yii\db\ActiveQuery;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * VindulosningController implements the CRUD actions for CalendarEvent model.
 */
class VindulosningController extends Controller
{

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

//    public function init()
//    {
//
////        Yii::$app->user->identity->role = "broker";
////        Yii::$app->user->identity->role = "director";
////        Yii::$app->user->identity->role = "partner";
//        Yii::$app->user->identity->role = "superadmin";
//
//        parent::init(); // TODO: Change the autogenerated stub
//    }

    public function actionIndex()
    {

        $data = $this->getPropertyDetailsQuery();
        $properties = $data["query"];

        $dataProvider = new ActiveDataProvider([
            'query' => $properties,
            'pagination' => false
        ]);


        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ["visible" => $this->renderPartial('partials/index', compact('dataProvider'))];
        }

        $dropdown = $data["dropdown"];

        Yii::$app->view->params['index'] = 'active';

        return $this->render('index', compact('dropdown', 'dataProvider'));
    }


    public function actionCreate()
    {

        $data = $this->getPropertyDetailsQuery();
        $properties = $data["query"]->andWhere(['property_details.is_visible' => 1]);


        $dataProvider = new ActiveDataProvider([
            'query' => $properties,
            'pagination' => false
        ]);

        $vindulosning = new Vindulosning();

        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;

            if (Yii::$app->request->isGet) return ["template" => $this->renderPartial('partials/create', compact('dataProvider'))];

            $hostInfo = Yii::$app->request->hostInfo;
            return ($vindulosning->load(Yii::$app->request->post()) && $vindulosning->save())
                ? "{$hostInfo}/eiendommer/reklame?view={$vindulosning->view}&id={$vindulosning->id}" : false;
        }


        $dropdown = $data["dropdown"];

        Yii::$app->view->params['create'] = 'active';

        return $this->render('create', compact('dropdown', 'dataProvider', 'vindulosning'));
    }


    public function actionChangeVisible()
    {
        if (!Yii::$app->request->isAjax) {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
        $property = Yii::$app->request->post("property");

        return PropertyDetails::updateAll(["is_visible" => $property["is_visible"]], ["id" => $property["id"]])
            ? "success" : "error";
    }


    /**
     * @return array
     */
    private function getPropertyDetailsQuery()
    {
        /** @var User $user */
        $user = Yii::$app->user->identity;

        switch ($user->role) {
            case "broker" :
                $dropdown = [];
                $employeesIds = [$user->web_id];
                break;
            case "director" :
                $dropdown = [];
                $employeesIds = ArrayHelper::getValue($user->department->users, "web_id");
                break;
            case "partner" :
                $dropdown = ["key" => "office_id", "items" => ArrayHelper::map($user->partner->department, "web_id", "navn")];
                $office_id = Yii::$app->request->get('office_id', $user->id_avdelinger);
                $employeesIds = ArrayHelper::getColumn(Department::getAnsatteUsersData($office_id), "web_id");
                break;
            default : // $user->role === superadmin
                $dropdown = ["key" => "partner_id", "items" => ArrayHelper::map(Partner::find()->all(), "id", "name")];
                $partner_id = Yii::$app->request->get('partner_id', $user->partner->id);
                $employeesIds = ArrayHelper::getColumn(Partner::getAnsatteUsersData($partner_id), 'web_id');
        }


//        $partner_id = Yii::$app->request->get('partner_id', $user->partner->id);
//
//        $employeesIds = ArrayHelper::getColumn(Partner::getAnsatteUsersData($partner_id), 'web_id');


        $propertyDetailsQuery = PropertyDetails::find()->select([
            '`property_details`.*',
            'IFNULL(`property_details`.`oppdragsnummer__prosjekthovedoppdrag`, UUID()) as `unique_group`'
        ])->andWhere([
            'property_details.arkivert' => 0,
            'property_details.vispaafinn' => -1
        ])->andWhere(['or',
            ['property_details.solgt' => 0],
            'DATE_ADD(STR_TO_DATE(`property_details`.`akseptdato`, "%d.%m.%Y"), INTERVAL 30 DAY) >= CURRENT_DATE()'
        ])->andWhere(['or',
            ['property_details.ansatte1_id' => $employeesIds],
            ['property_details.ansatte2_id' => $employeesIds]
        ]);

        return [
            "query" => $propertyDetailsQuery,
            "dropdown" => $dropdown
        ];
    }
}
