<?php


namespace frontend\controllers;


use backend\controllers\actions\PotentialClientsDataTableAction;
use common\components\Befaring;
use common\components\SesMailer;
use common\components\SnsComponent;
use common\components\StaticMethods;
use common\models\ArchiveForm;
use common\models\CalendarEvent;
use common\models\Forms;
use common\models\Image;
use common\models\Mail;
use common\models\PropertyDetails;
use common\models\PropertyEvent;
use common\models\Sms;
use common\models\User;
use frontend\assets\BefaringAsset;
use frontend\components\PdfGenerator;
use Yii;
use yii\db\ActiveQuery;
use yii\db\Expression;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class BefaringController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'potential-table' => [
                'class' => PotentialClientsDataTableAction::class
            ]
        ];
    }

//    public $id;
    public function beforeAction($action)
    {
        $id = Yii::$app->request->get('id');
        if (!$id || !Befaring::checkPropertyId($id)) {
            // throw new NotFoundHttpException("Siden finnes ikke.");
        }

        $this->layout = 'befaring';
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function actionIndex($id)
    {
        $property = PropertyDetails::findOne(['id' => $id]);

        $sellers = join(', ', ArrayHelper::getColumn($property->sellers, 'name'));

        return $this->render('index', compact('property', 'sellers'));
    }

    public function actionLike($id)
    {
        return $this->redirect('/befaring/index/' . $id);
    }

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionOppdrag($id)
    {
        Yii::$app->view->registerCssFile('/js/unitegallery-master/package/unitegallery/css/unite-gallery.css');
        $action = 'action' . ucfirst(Yii::$app->request->get('view'));
        if ($this->hasMethod($action)) {
            return $this->$action($id);
        }
        throw new NotFoundHttpException("Siden finnes ikke.");
    }


    /**
     * @param $id
     * @return false|string
     * @throws NotFoundHttpException
     */
    public function actionDetaljer($id)
    {
        $property = PropertyDetails::find()
            ->where(['id' => $id])
            ->andWhere(['not', ['lat' => null, 'lng' => null]])->one();

        if (!$property) {
            throw new NotFoundHttpException("Siden finnes ikke.");
        }
        $neighbours = $property->propertyNeighbourhoods;

        return $this->render('oppdrag/detaljer', compact('property', 'neighbours'));
    }


    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionSingle($id)
    {
        if (!Yii::$app->request->isAjax) {
            throw new NotFoundHttpException("Siden finnes ikke.");
        }
        $property = PropertyDetails::find()
            ->where(['id' => $id])->andWhere(['not', ['lat' => null, 'lng' => null]])
            ->andWhere(['not', ['oppdragsnummer' => null]])->one();
        $neighbours = $property->propertyNeighbourhoods;
        return $this->renderPartial('oppdrag/detaljer/_property-info', compact('property', 'neighbours'));
    }


    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     * @throws \yii\base\InvalidConfigException
     */
    public function actionImages($id)
    {
        if (!Yii::$app->request->isAjax) {
            throw new NotFoundHttpException("Siden finnes ikke.");
        }

        Yii::$app->view->registerJsFile('js/unitegallery-master/package/unitegallery/js/unitegallery.min.js', ['depends' => BefaringAsset::className()]);
        Yii::$app->view->registerJsFile('js/unitegallery-master/package/unitegallery/themes/compact/ug-theme-compact.js', ['depends' => BefaringAsset::className()]);
        Yii::$app->view->registerJsFile('js/dwelling-detail.js?v=', ['depends' => BefaringAsset::className()]);

        $images = Image::find()->where(['propertyDetailId' => $id])->all();
        return $this->renderAjax('oppdrag/detaljer/_bilder', compact('images'));
    }


    /**
     * @return false|string
     * @throws NotFoundHttpException
     */
    public function actionAll()
    {
        if (!Yii::$app->request->isAjax) {
            throw new NotFoundHttpException("Siden finnes ikke.");
        }

        $filter = Yii::$app->request->get('filter') ?? null;


        $property = PropertyDetails::find()
            ->select(["id", "CONCAT(`adresse`, ', ', `postnummer`, ' ',  `poststed`) AS address", "lat", "lng"])
            ->andWhere(['not', ['lat' => null, 'lng' => null]])->andWhere(['not', ['oppdragsnummer' => null]]);

        if ($filter) {
            $property = $property->andWhere(['>=', 'byggeaar', $filter['year'] - 1])
                ->andWhere(['or',
                    ['between', 'prom', $filter['meter'] - 10, $filter['meter'] + 10],
                    ['prom' => null]
                ])
                ->andWhere(['or',
                    ['between', 'salgssum', $filter['price'] - 500000, $filter['price'] + 500000],
                    ['salgssum' => null],
                    ['salgssum' => '']
                ])
                ->orWhere(['id' => Yii::$app->request->get('id')]);
        }

        $property = $property->asArray()->all();
        return json_encode($property);
    }


    public function actionCalendar($id)
    {
        if (Yii::$app->request->isAjax) {
            if (!$date = Yii::$app->request->post('date')) {
                return json_encode([]);
            }
            if ($eventId = Yii::$app->request->post('remove')) {

                if ($eventModel = PropertyEvent::findOne(['property_id' => $id, 'start_time' => $date, 'event_id' => $eventId])) {
                    $eventModel->delete();
                    return $eventId;
                }
            }
            if (!$data = Yii::$app->request->post('data')) {
                return json_encode([]);
            }

            $data = json_decode($data);
            $calendarEvent = CalendarEvent::findOne(['id' => $data]);
            // echo $date;
            PropertyEvent::deleteAll(['property_id' => $id, 'start_time' => $date, 'event_id' => $calendarEvent->id]);
            $modelPE = new PropertyEvent();
            $modelPE->property_id = $id;
            $modelPE->event_id = $calendarEvent->id;
            $modelPE->start_time = $date;
            if (!$modelPE->save()) {
            }
            return json_encode($id);
        }
        $propertyEvens = [];

        foreach (PropertyEvent::find()->where(['property_id' => $id])->all() as $propertyEven) {
            $propertyEven->event->start = $propertyEven->start_time;
            $propertyEvens[$propertyEven->id] = $propertyEven->event->attributes;
            $propertyEvens[$propertyEven->id]['start'] = $propertyEven->start_time;
        }
        $events = CalendarEvent::find()->indexBy('id')->asArray()->all();
        $property = PropertyDetails::findOne(["id" => $id]);
        return $this->render('calendar', compact('events', 'propertyEvens', 'property'));
    }

    public function actionDitTeam($id)
    {
        $property = PropertyDetails::findOne(['id' => $id]);

        return $this->render('dit-team', compact('property'));
    }

    public function actionNode($id)
    {
        $model = new Sms();
        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                $smsSender = new SnsComponent();
                $smsSender->publishSms($model->message, $model->phone);
                Yii::$app->session->setFlash('success', 'Vellykket sendt');
//                return Json::encode(['success' => 'Vellykket sendt']);
            }
//            return Json::encode($model->getErrors());
        }
        return $this->render('node', [
            'model' => $model
        ]);

    }

    public function actionPotentialClients($id)
    {
        $model = new Forms;

        $formTypes = Forms::find()
            ->select('type')
            ->where(['in', 'type', ['salgsoppgave', 'visningsliste', 'budvarsel', 'boligvarsling']])
            ->distinct()
            ->all();

        $formTypes = ArrayHelper::map($formTypes, 'type', 'type');

        $propTypes = PropertyDetails::find()
            ->select([
                "(CASE WHEN property_details.type_eiendomstyper NOT IN ('Leilighet', 'Enebolig','Tomannsbolig','Hytte','Rekkehus')
                  THEN 'Andre'
                  WHEN property_details.type_eiendomstyper IN ('Leilighet', 'Enebolig','Tomannsbolig','Hytte','Rekkehus')
                  THEN type_eiendomstyper END) AS type_eiendomstyper",
                "(CASE WHEN property_details.type_eiendomstyper NOT IN ('Leilighet', 'Enebolig','Tomannsbolig','Hytte','Rekkehus')
                  THEN 'Andre'
                  WHEN property_details.type_eiendomstyper IN ('Leilighet', 'Enebolig','Tomannsbolig','Hytte','Rekkehus')
                  THEN type_eiendomstyper  END) AS type"
            ])
            ->groupBy('type')
            ->orderBy([new Expression('FIELD(type, "Leilighet", "Enebolig", "Tomannsbolig", "Rekkehus", "Hytte", "Forretning", "Tomt", "Andre")')])
            ->asArray()
            ->distinct()
            ->all();

        $propTypes = ArrayHelper::map($propTypes, 'type_eiendomstyper', 'type_eiendomstyper');
        $property = PropertyDetails::findOne($id);
        $salgssum = PropertyDetails::find()->select(['MIN(salgssum) as min', 'MAX(salgssum) as max'])->asArray()->one();

        return $this->render('potential', compact('model', 'formTypes', 'propTypes', 'property', 'salgssum'));
    }

    /**
     * @return false|string
     */
    function actionMapCoords()
    {
        $className = Forms::tableName();
        $coords = Forms::find()
            ->joinWith(['postNumber', 'propertyDetails'], false)// TODO: set universal postnumber relation for all coord manipulation classes
            ->where(['NOT', ['all_post_number.post_number' => NULL]])
            ->select("
                {$className}.id, 
                {$className}.post_number, 
                all_post_number.lat, 
                all_post_number.lon
            ");
        $coords = $coords->andWhere(['forms.type' => Forms::getInterestedTypes()]);

        $coords = $coords->asArray()->all();
        $result = [];
        foreach ($coords as $c) {
            if (!isset($result[$c['lat']])) {
                $result[$c['lat']] = [];
            }
            if (!isset($result[$c['lat']][$c['lon']])) {
                $result[$c['lat']][$c['lon']] = [];
            }
            $result[$c['lat']][$c['lon']][] = $c['post_number'];
        }
        $coords = [];
        $i = 0;
        foreach ($result as $lat => $c) {
            foreach ($c as $lon => $postNumbers) {
                $coords[$i] = [
                    'lat' => floatval($lat),
                    'lng' => floatval($lon),
                    'postNumbers' => $postNumbers,
                ];
                $i++;
            }
        }
        return json_encode($coords);
    }

    /**
     * @return string
     */
    public function actionMailing()
    {
        $request = Yii::$app->request;
        $model = new Mail;
        $emails = [];
        $model->setScenario($request->post("selger")
            ? Mail::SCENARIO_BEFARING_CALENDAR_SELGER : Mail::SCENARIO_BEFARING_CALENDAR);

        if ($request->isPost && $model->load($request->post())) {
            if (!$model->validate()) {
                return Json::encode($model->getErrors());
            }
            $mailer = new SesMailer;
            $model->message .= str_repeat("\n", 3);

            if ($model->scenario == Mail::SCENARIO_BEFARING_CALENDAR_SELGER) {
                /** @var User $users */
                $users = ArchiveForm::find()->where(["in", "id", $model->emails])->all();
                foreach ($users as $user) {
//                    $phone = StaticMethods::convertPhone($user->phone);
//                    $model->message .= "\n\n{$user->name}\nTelefon: {$phone}\nE-post: {$user->email}";
                    array_push($emails, $user->email);
                }
            } else {
                array_push($emails, $model->email);
            }


            if ($send_broker_email = $request->post('send_broker')) {
                array_push($emails, $send_broker_email);
            }

            $model->message = $this->renderPartial("@frontend/views/emails/client/befaring_calendar", [
                'text' => str_replace("\n", "<br>", $model->message)
            ]);

            $response = $mailer->sendMail($model->message, $model->subject, $emails, $model->from);

            if (!$mailer->fails()) {
                return Json::encode(['success' => 'Vellykket sendt']);
            }

            return Json::encode($response);
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionPdf($id)
    {

        /** @var PropertyDetails $property */
        $property = PropertyDetails::findOne(['property_details.id' => $id]);

        if (!$property)
            throw new NotFoundHttpException('The requested page does not exist.');

        $query = Forms::find()
            ->joinWith(['propertyDetails'])
            ->andFilterWhere(['between', 'property_details.prisantydning', '100000', '6000000'])
            ->andFilterWhere(['between', 'property_details.prom', '40', '100']);

        $lat = deg2rad((float)59.9139);
        $lng = deg2rad((float)10.7522);
        $earthR = 6371 * 1000;
        $query->joinWith(['allPostNumber']);
        $query->andWhere([
            '<=', "acos(sin({$lat})*sin(radians(all_post_number.lat))+cos({$lat})*cos(radians(all_post_number.lat))*cos(radians(all_post_number.lon)-{$lng})) * {$earthR}", 1000
        ]);
        $query->andWhere(['not', ['forms.post_number' => null, 'all_post_number.id' => null]]);

        $range = [
            'from' => time() - 60 * 60 * 24 * 30 * 0,
            'to' => time() - 60 * 60 * 24 * 30 * 9
        ];

        $query->andFilterWhere(['between', 'forms.created_at', $range['to'], $range['from']]);

        $this->view->title = $property->adresse;
        $this->view->params['mulige_kjpere'] = $query->andWhere(['forms.type' => Forms::getInterestedTypes()])->count();
        $version = $property->isOwnedSchalaPartners() ? 1 : 2;
        $propertyEvents = PropertyEvent::find()
            ->joinWith(['event'])
            ->where(['property_id' => $id])
            ->andWhere(['BETWEEN', 'start_time',new Expression("DATE_FORMAT(NOW() - INTERVAL 1 MONTH, '%Y-%m-01')") , new Expression("DATE_FORMAT(NOW() + INTERVAL 1 MONTH, '%Y-%m-31')")])
            ->all();
        Yii::$app->params['events'] = $propertyEvents;
//        return $this->renderPartial('/befaring/pdf/template_1/page_14');
        $pdf = new PdfGenerator($property, $version);
        $pdf->generate();

    }

}
