<?php


namespace common\widgets;


use common\models\CalendarEvent;
use yii\base\Widget;

class AddCalendar extends Widget
{
    public function run()
    {
        $model = new CalendarEvent();
        return $this->render('form', compact('model'));
        parent::run(); // TODO: Change the autogenerated stub
    }
}