<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%calendar_events}}".
 *
 * @property int $id
 * @property string $name
 * @property string $description
 * @property string $classes
 * @property string $start
 * @property int $created_at
 * @property int $updated_at
 */
class CalendarEvent extends ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%calendar_events}}';
    }

    public $start;

    public function behaviors()
    {
        return [TimestampBehavior::className()];
    }

    public function beforeSave($insert)
    {
        if(!$this->classes) {
            $this->classes = 'fc-event-danger fc-event-solid-success';
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['created_at', 'updated_at'], 'integer'],
            [['name', 'description', 'classes'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'description' => Yii::t('app', 'Description'),
            'classes' => Yii::t('app', 'Classes'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    public function getPropertyEvent() {
        return $this->hasMany(PropertyEvent::className(), ['property_id' => 'id']);
    }

    /**
     * {@inheritdoc}
     * @return CalendarEventQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new CalendarEventQuery(get_called_class());
    }
}
