<?php

namespace common\models;

use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "client".
 *
 * @property int $id
 * @property string $name
 * @property string $email
 * @property string $phone
 * @property string $status
 * @property string $post_number
 * @property int $last_contact
 * @property int $created_at
 * @property int $updated_at
 * @property int $blocked
 *
 * @property Forms[] $leads
 */
class Client extends ActiveRecord
{
    /**
     * The count hot leads.
     *
     * @var
     */
    public $hotCount;

    /**
     * The count hot leads.
     *
     * @var
     */
    public $coldCount;

    /**
     * Client consists the leads.
     *
     * @return ActiveQuery
     */
    public function getForms(): ActiveQuery
    {
        return $this->hasMany(Forms::class, ['client_id' => 'id']);
    }

    /**
     * Client has the lead.
     *
     * @return ActiveQuery
     */
    public function getLastForm(): ActiveQuery
    {
        return $this->hasOne(Forms::class, ['client_id' => 'id']);
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['last_contact', 'created_at', 'updated_at', 'blocked'], 'integer'],
            [['name', 'email'], 'string', 'max' => 255],
            [['phone'], 'string', 'max' => 30],
            [['status'], 'string', 'max' => 32],
            [['post_number'], 'string', 'max' => 4],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'email' => 'Email',
            'phone' => 'Phone',
            'status' => 'Status',
            'post_number' => 'Post Number',
            'last_contact' => 'Last Contact',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'blocked' => 'Bloked',
        ];
    }

    /**
     *  This method is overridden so that attributes and related objects can be accessed like properties.
     *
     * @param string $name
     *
     * @return mixed|string
     */
    public function __get($name)
    {
        if (in_array($name, ['status'])) {
            return \Yii::t('lead_log', $this->getAttribute($name));
        }

        return parent::__get($name);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLeads(){
        return $this->hasMany(Forms::className(), ['client_id' => 'id']);
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        if ($insert){// If Client is new
            $this->created_at = $this->created_at ? $this->created_at : time();
        }
        $this->updated_at = time();
        $this->last_contact = time();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}