<?php

namespace common\models;

use borales\extensions\phoneInput\PhoneInputValidator;
use common\components\SesMailer;
use common\components\SnsComponent;
use common\components\StaticMethods;
use console\components\MultyConnection;
use Exception;
use Yii;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use yii\db\ActiveRecordInterface;
use yii\db\Query;
use yii\helpers\ArrayHelper;


/**
 * This is the model class for table "forms".
 *
 * @property int $id
 * @property int $department_id
 * @property string $type
 * @property string $broker_id
 * @property int $source_id
 * @property string $source
 * @property string $name
 * @property int $delegated
 * @property string $post_number
 * @property string $phone
 * @property string $email
 * @property string $message
 * @property int $subscribe_email
 * @property int $contact_me
 * @property int $target_id
 * @property int $created_at
 * @property int $updated_at
 * @property int $send_sms
 * @property string $token
 * @property string $referer_source
 * @property string $address
 * @property string $dob
 * @property int $client_id
 * @property string $status
 * @property string $handle_type
 * @property int $request_phone_user_id
 * @property bool $favorite
 * @property string $url
 * @property string $surname
 * @property string $firebase_id
 * @property int $book_visning
 * @property int $partner_id
 * @property int $boligvarsling_id
 *
 * Fake attributes
 * @property string $booking_date
 *
 * @property LeadLog[] $delegatedDepartments
 * @property Partner $partner
 * @property Department $department
 * @property LeadLog[] $leadLogs
 * @property LeadLog $leadLastLog
 * @property Client $client
 * @property PropertyDetails $propertyDetails
 *
 * @property User $user
 * @property User $delegatedUser
 * @property \DateTime $request_phone_at
 *
 * @property bool $download_sales_report
 * @property AllPostNumber[] $allPostNumber
 * @property Boligvarsling $boligvarsling
 */
class Forms extends ActiveRecord
{
    public static $feedType = 'verdivurdering';

    /*Fake attribute*/
    public $megler_booking_date;

    /**
     * @param string $name
     * @param array|ActiveRecordInterface|null $records
     */
    public function populateRelation($name, $records){
        parent::populateRelation($name, $records); // TODO: Change the autogenerated stub
    }

    public $i_agree = false;

    public $subscribe_to_related_properties = false;

    /**
     * @var string;
     */
    public $latestLogType;

    /**
     * @var string
     */
    public $latestLogAt;

    /**
     * @var string
     */
    public $latestLogMessage;

    /**
     * @var string
     */
    public $departmentName;

    /**
     * @var string
     */
    public $belongsType;

    /**
     * For Gmaps Data-Tables
     */
    public $centerX;
    public $centerY;
    public $radius;

    public $area_real;

    public $propertyCost;

    // Scenarios
    const SCENARIO_BOOKING_VISNING = 'BOOKING_VISNING';// Coronavirus test form 15Mar2020,
    const SCENARIO_KONTAKT_MEG = 'KONTAKT MEG';// Side Form,
    const SCENARIO_BUDVARSEL = 'BUDVARSEL';// budvarsel
    const SCENARIO_SALGSSUM = 'PROPERTY CONTACT';
    const SCENARIO_VISNINGLISTE = 'VISNINGLISTE';
    const SCENARIO_SALGSOPPGAVE = 'SALGSOPPGAVE';
    const SCENARIO_API = 'API';
    const SCENARIO_OTHER = 'OTHER';
    const SCENARIO_MEGLER_BOOKING = 'MEGLER_BOOKING';

    //Key agrs
    const NOTE_LOG_TYPE = 'notat';

    private static $hotTypes = [
        "verdivurdering",
        "pristilbud",
        "kontakt",
        "meglerbooking",
        "kontakt_broker",
        "tender",
        "salgssum_landing",
        "salgssum",
        "skal_selge",
        //"book_visning",
        "e_takst",
        //"salgssum_venter",
        //"jobb",
    ];

    private static $coldTypes = [
        //"boligvarsling",
        "salgsoppgave",
        "budvarsel",
        "visningliste",
        // "selger",
        // "kjoper",
    ];

    private static $interestedTypes = [
        "salgsoppgave",
        "budvarsel",
        "visningliste",
        "salgssum_landing",
        "salgssum",
        "salgssum_venter",
    ];

    protected $emailSubjects = [
        'verdivurdering' => [
            'broker'=>'Ny verdivurdering',
        ],
        'skal_selge' => [
            'broker'=>'Ny skal_selge',
        ],
        'pristilbud' => [
            'broker'=>'Nytt pristilbud',
        ],
        'kontakt' => [
            'broker'=>'Ny meglerbooking',
        ],
        'meglerbooking' => [
            'broker'=>'Ny kontakt oss',
        ],
        'kontakt_broker' => [
            'broker'=>'Ny direkte kontakt',
        ],
        'salgssum' => [
            'broker'=>'Ny Salgssum på {{address}}',
        ],
        'budvarsel' => [
            'broker'=>'Ny budvarsel {{address}}',
        ],
        'salgssum_landing' => [
            'broker'=>'Ny salgssum på {{address}}',
        ],
        'book_visning' => [
            'broker' => 'Ny melding på visning på {{address}}',
            'client' => 'Visning på {{address}}'
        ],
        'jobb' => [
            'broker'=>'Ny jobb skjema',
        ],
        'salgsoppgave' => [
            'broker'=>'Salgsoppgave på {{address}}',
            'client'=>'Salgsoppgave på {{address}}',
        ],
        'e_takst' => [
            'broker'=>'Ny Е-takst',
        ],
    ];

    protected $messagesForResponse = [
        'visningliste' => 'Du er nå registrert.',
        'salgssum_venter' => 'Vi tar kontakt når boligen er solgt.',
        'salgssum' => 'Vi tar kontakt når boligen er solgt.',
        'budvarsel' => 'Du er nå registrert.',
        'salgsoppgave' => 'Vi har sendt deg salgsoppgave.',
        'verdivurdering' => 'Du vil snart bli kontaktet av en lokal megler.',
        'book_visning' => 'Du er påmeldt til visning. Vi kontakter deg for å avtale nærmere tidspunkt og hører du ikke fra oss er du velkommen til oppsatt visningstidspunkt.',
    ];


    /**
     * @return array
     */
    public function getSuccessResponse()
    {
        $message = $this->messagesForResponse[$this->type] ?? null;
        return [
            'success' => true,
            'message' => $message,
        ];
    }

    public function scenarios()
    {
        return [
            // TODO: fix scenarios relating to all forms
            self::SCENARIO_DEFAULT =>         [],
            self::SCENARIO_API =>             ['name', 'phone', 'type', 'email', 'post_number', 'address', 'message', 'company', 'source_id'],
            self::SCENARIO_KONTAKT_MEG =>     ['name', 'phone', 'type', /*email*/'post_number', /*address*/'broker_id', 'i_agree'],
            self::SCENARIO_SALGSSUM =>        ['name', 'phone', 'type', 'email', 'post_number', /*address*/'broker_id', 'i_agree', 'target_id', 'subscribe_email', ],
            //Merged: dev-clone -> ringeliste
            self::SCENARIO_BOOKING_VISNING => ['name', 'phone', 'type', 'email', 'post_number', /*address*/'broker_id', 'i_agree', 'target_id', 'subscribe_email', 'contact_me', 'message', 'book_visning', 'send_sms', 'download_sales_report', 'booking_date'],
            self::SCENARIO_BUDVARSEL =>       ['name', 'phone', 'type', 'email', 'post_number', /*address*/'broker_id', 'i_agree', 'target_id', 'subscribe_email', 'contact_me',/*message*/ ],
            self::SCENARIO_OTHER =>           ['name', 'phone', 'type', 'email', 'post_number', 'address', 'broker_id', 'i_agree', 'target_id', 'subscribe_email', 'contact_me', 'message', 'department_id', 'delegated', ],
            self::SCENARIO_VISNINGLISTE =>    ['name', 'phone', 'type', 'email', 'post_number', /*address*/'broker_id', 'i_agree', 'target_id', 'subscribe_email', 'contact_me', 'message', 'send_sms', ],
            self::SCENARIO_SALGSOPPGAVE =>    ['name', 'phone', 'type', 'email', 'post_number', /*address*/'broker_id', 'i_agree', 'target_id', 'subscribe_email', 'contact_me',/*message*/ 'send_sms', 'boligvarsling_id', 'subscribe_to_related_properties', ],
            self::SCENARIO_MEGLER_BOOKING =>  ['name', 'phone', 'type', 'email', 'post_number', 'broker_id', 'i_agree', 'target_id', 'subscribe_email', 'contact_me', 'message', 'megler_booking_date'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'forms';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            // Types
            [['handle_type', 'status', 'type', 'name', 'phone', 'token', 'url', 'broker_id', 'address'], 'string', 'max' => 255],
            [['i_agree', 'department_id', 'source_id', 'delegated', 'subscribe_email', 'contact_me', 'target_id', 'client_id', 'created_at', 'updated_at', 'send_sms', 'dob', 'book_visning', 'partner_id', 'boligvarsling_id'], 'integer'],
            [['message'], 'string'],
            [['source', 'referer_source'], 'string', 'max' => 1024],
            [['email'], 'email'],
            [['phone'], 'isPhone'],
            [['favorite', 'download_sales_report', 'subscribe_to_related_properties'], 'boolean'],

            // Edit
            [['post_number', 'email', 'name'], 'trim'],
            ['post_number', 'match', 'pattern' => '/^\d{3,4}$/', 'message' => 'Postnummer må være et heltall.'],

            // Required
            [['post_number', 'type', 'phone', 'name', 'created_at', 'updated_at'], 'required'],
            [['book_visning'], 'required', 'requiredValue' => '1', 'message' => 'Bekreft at du har lest og forstått informasjonen om Coronavirus', 'on' => self::SCENARIO_BOOKING_VISNING],
            [['i_agree'], 'required', 'requiredValue' => '1', 'message' => 'Bekreft at du har lest vilkårene'],
            [['megler_booking_date'], 'required', 'on' => self::SCENARIO_MEGLER_BOOKING],
            [['email'], 'required', 'on' => self::SCENARIO_SALGSOPPGAVE,],
            [['email'], 'required', 'when' => function ($model) {
                return $model->subscribe_email == true;
            }],

            // Relations
            [['target_id'], 'exist', 'targetClass' => PropertyDetails::class, 'targetAttribute' => 'id'],
            [['broker_id'], 'exist', 'targetClass' => User::class, 'targetAttribute' => 'web_id'],
        ];
    }

    /**
     * We accept this phone number.
     *
     * @param $attribute
     * @param $params
     *
     * @return bool
     */
    public function isPhone($attribute, $params)
    {
        if (!preg_match('/^\+\d{1,2}\d{8,10}$/', $this->phone)) {
            $this->addError($attribute, 'Formatet til Telefon er ugyldig.');

            return false;
        }

        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type' => 'Type',
            'source_id' => 'Kilde ID',
            'source' => 'Kilde',
            'name' => 'Navn',
            'delegated' => 'Delegert',
            'post_number' => 'Postnummer',
            'phone' => 'Telefon',
            'email' => 'Epost',
            'message' => 'Beskjed',
            'subscribe_email' => 'Abonner via e-post',
            'contact_me' => 'Kontakt meg',
            'target_id' => 'Target ID',
            'created_at' => 'Opprettet kl',
            'updated_at' => 'Endret kl',
            'send_sms' => 'Send Sms',
            'token' => 'Token',
            'broker_id' => 'Megler ID',
            'department_id' => 'Departmen Id',
            'address' => 'Addresse',
            'dob' => 'Fodselsdato',
            'handle_type' => 'Loggforing',
            'status' => 'Status',
            'client_id' => 'Client Id',
            'favorite' => 'Favorite',
            'url' => 'Url',
            'partner_id' => 'Partner ID',
            'booking_date' => 'Date',
            'megler_booking_date' => 'Dato',
            'notify_at' => 'Varsling kl.',
        ];
    }

    /**
     *  This method is overridden so that attributes and related objects can be accessed like properties.
     *
     * @param string $name
     *
     * @return mixed|string
     */
    public function __get($name)
    {
        if (in_array($name, ['status', 'handle_type'])) {
            return \Yii::t('lead_log', $this->getAttribute($name));
        }

        return parent::__get($name);
    }

    public function convertSymboles() {
        $origin = ['Ø','ø','Å','å', 'ü', 'Ü', 'æ', 'Æ'];
        $replaceTo = ['&#216;','&#248;','&#197;','&#229;', '&#252;', '&#220;', '&#230;', '&#198;'];
        $attributes = ['email' , 'message'];
        foreach ($attributes as $key => $val){
            $this[$val] = str_replace($origin, $replaceTo, $this[$val]);
        }
        return  true;
    }

    /**
     * @return bool
     */
    public function beforeValidate()
    {
        $this->convertSymboles();

        $this->phone = str_replace(['(', ')', '-', '+', '.', ' '], '', $this->phone);
        $phoneLength = strlen($this->phone);

        if ($phoneLength === 8) {
            $this->phone = "+47{$this->phone}";
        }

        if ($phoneLength > 8 && strpos($this->phone,'+') === false) {
            $this->phone = "+{$this->phone}";
        }

        return parent::beforeValidate();
    }

    /**
     * Extend the ActiveRecord::afterValidate()
     */
    public function afterValidate()
    {
        parent::afterValidate();
    }

    /**
     * Add a log once to the lead.
     *
     * @param array $attributes
     */
    public function addLogOnce(array $attributes): void
    {
        if (!is_array($attributes) || empty($attributes)) {
            return;
        }

        $attributes['user_id'] = Yii::$app->user->identity->web_id;

        $exists = $this->getLogs()->where($attributes)->exists();

        if (!$exists) {
            $log = new LeadLog;
            $log->setAttributes($attributes + ['lead_id' => $this->id]);
            $log->save(false);
        }
    }

    /**
     * Add Log to lead(form)
     * @param $type
     * @param $message
     * @param $notifyAt
     * @param $informInAdvance
     * @return bool
     */
    public function addLog($type, $message, $notifyAt = null, $informInAdvance = null)
    {
        $log = new LeadLog();
        $log->created_at = $log->updated_at = time();

        $log->message = $message;
        $log->type = $type;

        if ($notifyAt) {
            $log->notify_at = strtotime($notifyAt);

            $this->updateAttributes([
                'notify_note' => $log->message,
                'notify_at' => $log->notify_at
            ]);
        }

        $this->link('logs', $log);

        //TODO: set this types as Forms public param also fix usage in project
        //TODO: add separate functions for status and handle type changes and fix them on project
        $handleTypes = [
            '1014',
            '1020',
            '1017',
            '1011',
            '1009',
            '1013',
            '1008',
            '1018',
        ];

        $statuses = [
            '1002',
            '1004',
            '1005',
            '1001',
            '1014',
            '1020',
            '1017',
            '1011',
            '1009',
            '1013',
            '1008',
            '1018',
        ];

        if (in_array($type, $handleTypes)){
            $this->handle_type = $type;
        }

        if (in_array($type, $statuses)){
            $this->status = $type;
        }
        
        if (!$this->getIsNewRecord()){
            $this->save();
        }
    }

    public function getBoligvarsling()
    {
        return $this->hasOne(Boligvarsling::class, ['id' => 'boligvarsling_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLogs()
    {
        return $this->hasMany(LeadLog::className(), ['lead_id' => 'id'])
            ->orderBy([
                'lead_log.updated_at' => SORT_DESC,
                'lead_log.id' => SORT_DESC,
            ]);
    }

    /**
     * @return ActiveQuery
     */
    public function getLatestLog()
    {
        return $this->hasOne(LeadLog::class, ['lead_id' => 'id'])
            ->orderBy([
                'lead_log.id' => SORT_DESC
            ]);
    }

    public function getAllPostNumber()
    {
        return $this->hasOne(AllPostNumber::class, ['post_number' => 'post_number']);
    }

    public function getReminder()
    {
        return $this->hasOne(LeadLog::class, ['lead_id' => 'id'])
            ->where([
                'type' => '1014',
                'user_id' => Yii::$app->user->identity->web_id
            ])
            ->orderBy([
                'id' => SORT_DESC
            ])
            ->alias('reminderLeadLog');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDelegatedUser()
    {
        return $this->hasOne(User::class, ['web_id' => 'delegated'])
            ->from(User::tableName() . ' u2');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser(){
        return $this->hasOne(User::class, ['web_id' => 'broker_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     * @throws \yii\base\InvalidConfigException
     */
    public function getDepartment()
    {
        return $this->hasOne(Department::class, ['web_id' => 'department_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     * @throws \yii\base\InvalidConfigException
     */
    public function getPartner()
    {
        return $this->hasOne(Partner::class, ['id' => 'partner_id']);
    }

    /**
     * Delegate Lead to broker
     * @param bool $user \common\models\User
     * @param bool|string $logType
     * @param bool $isForce
     * @throws Exception
     * @throws \Throwable
     */
    public function delegate($user = false, $logType = false, $isForce = false)
    {
        // Select attached user or default if attached user is missing
        /** @var User $user */
        $user = $user ? $user : User::findOne(['web_id' => $this->broker_id]);
        if (
            !$user
            || $user->inaktiv_status = 0
            || $user->dismissaldate && $user->dismissaldate < time()
        ){// Delegate to director if user is missing or fiered or inaktiv
            $id = $user ? $user->web_id : 'none existing';
            $user = 'undefined';
            if (!$this->department){
                return;
            }
            $user = $this->department->director;

            self::slackMessage("Lead({$this->id}) delegate attempt to brokker($id) failed.\n Delegated to {$user->navn}({$user->web_id})({$user->role})");
        }

        $isNew = $this->justNew();
        $logType = '1002';// type delegert
        $this->delegated = $this->broker_id; // Init from which user the lead was delegated from
        $this->broker_id = $user ? $user->web_id : null;
        $this->department_id = $user->id_avdelinger;

        $this->save();
        // TODO: following condition is useless
        $message = "<span>{$user->navn}</span> <span>{$this->department->short_name}</span>";
        
        $this->addLog($logType,$message);

        if ($this->source_id !== 0 ){ //Means that not from api or created from admin panel
            $this->sendSms([
                'broker' => [
                    'enabled' => true,
                    'message' => false,
                    'phone' => $user->mobiltelefon,
                    'name' => $user->navn,
                    'web_id' => $user->web_id,
                ],
                'client' => [
                    'enabled' => $isNew,
                    'message' => false,
                    'phone' => $this->phone,
                    'name' => false,
                ],
            ]);
            $this->sendEmailToBrokerOrDirector($user);
        }
    }

    /**
     * Ufordelt Lead to Department
     * @param $dep Department
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function ufordelt($dep)
    {
        $this->department_id = $dep->web_id;
        $this->broker_id = null;
        $this->save();
        $message = "<span>{$dep->short_name}</span>";
        $this->addLog('1004', $message);
        $this->sendSms([
            'broker' => [
                'enabled' => true,
                'message' => false,
                'phone' => $dep->director->mobiltelefon,
                'name' => $dep->director->navn,
                'web_id' => $dep->director->web_id,
            ],
            'client' => [
                'enabled' => false,
                'message' => false,
                'phone' => $this->phone,
                'name' => false,
            ],
        ]);
        $this->sendEmailToBrokerOrDirector($dep->director);
    }


    /**
     * Delegate Lead to Department
     * @param bool | \common\models\Department $dep
     * @param bool | \common\models\Forms $lead
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function allocate($dep = false, $lead = false)
    {
        //TODO: optimise querys and function
        $lead = $lead ? $lead : $this;
        $logType = '1005';

        if(!$dep || ($this->department_id && parent::__get('status') != '1005')){
            if ($this->department_id !== null){
                $dep = $this->department;
            }else{
                $dep = Department::find()->joinWith(['postNumbers'])
                    ->where(['post_number.index' => $this->post_number, 'department.inaktiv' => 0])
                    ->one()
                ;
            }
            if ($dep){
                $logType = '1004';
            }else{
                $dep = $this->closestDepartment($lead->post_number);
            }
        }

        $director = $dep->director;

        $lead->department_id = $dep->web_id;
        $isNew = $this->justNew();
        
        $lead->save();
        $lead->addLog($logType, $dep->short_name);

        if (!$director){
            echo "\n no director \n";
            return;
        }
        $lead->sendSms([
            'broker' => [
                'enabled' => true,
                'message' => false,
                'phone' => $director->mobiltelefon,
                'name' => $director->navn,
                'web_id' => $director->web_id,
            ],
            'client' => [
                'enabled' => $isNew,
                'message' => false,
                'phone' => $this->phone,
                'name' => false,
            ],
        ]);
        $lead->sendEmailToBrokerOrDirector($director);
    }

    /**
     * Trying to attach lead to some broker or company
     * @throws \yii\base\InvalidConfigException
     * @throws Exception
     * @throws \Throwable
     */
    public function attachLead(){
        if ($this->broker_id) {
            $this->delegate();
        } else {
            $this->allocate();
        }

        if (
            (
                $this->hasType('visningliste')
                || $this->hasType('budvarsel')
                || $this->hasType('salgsoppgave')
            )
            && $this->contact_me
        ) {
            // Add form duplicate if contact checked
            $subLead = clone $this;
            $subLead->isNewRecord = true;
            $subLead->id = null;
            $subLead->type = 'skal_selge';
            $subLead->save();
        }
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLeadLogs()
    {
        return $this->hasMany(LeadLog::class, ['lead_id' => 'id']);
    }

    /**
     * @return ActiveQuery
     */
    public function getPropertyDetails()
    {
        return $this->hasOne(PropertyDetails::class, ['id' => 'target_id']);
    }

    /**
     * Lead belongs to a property.
     *
     * @return ActiveQuery
     */
    public function getProperty()
    {
        return $this->hasOne(PropertyDetails::class, ['id' => 'target_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     * This relation is deprecated use Form::handle_type instead
     */
    public function getLeadLastLog()
    {
        $formsId = $this->id ? $this->id : 'forms.id';
        $lastLead = (new Query())
            ->select(['id'])
            ->from('lead_log')
            ->where("lead_log.lead_id = {$formsId}")
            ->andWhere(['<>','lead_log.type','1006'])
            ->orderBy([
                'lead_log.updated_at' => SORT_DESC,
                'lead_log.id' => SORT_DESC,
            ])
            ->limit(1)
        ;
        return $this->hasOne(LeadLog::class, ['lead_id' => 'id'])
            ->andOnCondition(['=', 'lead_log.id', $lastLead])
        ;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDelegatedDepartments()
    {
        return $this->hasMany(LeadLog::className(), [
            'lead_id' => 'id',
        ])
        ->andOnCondition(['lead_log.type' => '1005'])
        ->select(['lead_id', 'message',]);
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        $db = Yii::$app->db;
        /** @var MultyConnection $db */
        $this->broker_id = $this->broker_id ? $this->broker_id : null;

        if ($insert) { // If lead is new

            if (!is_console()) {
                $cookies = Yii::$app->request->cookies;

                if ($cookies->has('referrer')) {
                    $this->referer_source = $cookies->get('referrer');
                }

                $this->source = Yii::$app->request->referrer;
            }

            $this->created_at = $this->created_at ? $this->created_at : time();

            $client = Client::findOne(['phone' => $this->phone]);
            if (!$client){
                // Create Client
                $client = new Client();
                $client->status = $this->handle_type;
            }
            $client->name = $this->name;
            $client->email = $this->email;
            $client->phone = $this->phone;
            $client->post_number = $this->post_number;
            $client->save();
            $this->client_id = $client->id;

        }
        
        if (!$this->department_id && $this->broker_id ){
            if ($this->user){
                $this->department_id = $this->user->id_avdelinger;
            }
        }

        if (!$this->partner_id && $this->department_id ){
            $this->partner_id = $this->department->partner_id;
        }
        $this->updated_at = time();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @param bool $insert
     * @param array $changedAttributes
     */
    public function afterSave($insert, $changedAttributes)
    {
        if ($insert){
            $this->addLog('1001', "<a href='{$this->source}'>{$this->source}</a>");

            if ($this->handle_type && $this->phone){
                $client = Client::findOne(['phone'=>$this->phone]);
                if ($client){
                    $d = date("d.m.y",$client->last_contact);
                    $this->addLog(
                        self::NOTE_LOG_TYPE,
                        "Siste kontakt var {$d}. {$this->handle_type}"
                    );
                }
            }
        }

        if(array_key_exists('handle_type',$changedAttributes)){// Update client if form handle type is changed
            $this->client->status = $this->handle_type;
            $this->client->save();
        }

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    /**
     * Che may form be logged and sms notifyed
     */
    public static function mayLogAndSms(){
        $weekDay = intval(date('N'));
        $hourMinute = intval(date('i'));
        $dayHour = intval(date('H'));
        $dayHour += $hourMinute / 60;// hour with minutes

        $start = 9 - ($weekDay > 5/*is weekend*/ ? 0 : .5)/*half of hour*/;
        $end = 17;
        return $dayHour > $start && $dayHour < $end;
    }

    /**
     * Send sms to broker and customer if lead is just registered or delegated and its work time
     *
     * @param array[]|bool $smsMap
     *
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    private function sendSms($smsMap = false){
        $defaultSmsMap = [
            'broker' => [
                'enabled' => true,
                'message' => false,
                'phone' => false,
                'name' => false,
            ],
            'client' => [
                'enabled' => true,
                'message' => false,
                'phone' => $this->phone,
                'name' => false,
            ],
        ];
        $smsMap = $smsMap ? $smsMap : $defaultSmsMap;
        $smsSender = new SnsComponent();

        if (!isset($smsSender->smsText[$this->type])) {// Exit if there is no messgae for this type of form
            return;
        }
        $smsTextsMap = isset($smsSender->smsText[$this->type]) ? $smsSender->smsText[$this->type] : [];

        /** @var PropertyDetails $property */
        $property = isset( $this->target_id ) && $this->target_id ?
            (PropertyDetails::find()
                ->joinWith(['propertyDoc'])
                ->where(['property_details.id' => $this->target_id])
                ->select([
                    'property_details.adresse',
                    'property_details.oppdragsnummer',
                    'docs.urldokument',
                    'property_details.id'])
                ->one()
            ) : false
        ;

        if ($this->isHot()) {
            $this->token = StaticMethods::generateToken(15);
            $this->update();
        }

        //TODO: generate inside $smsMap loop
        $vars = [
            'broker' => $smsMap['broker']['name'],
            'department' => $this->department->navn,
            //TODO: generate  by pretty url
            'link' => Yii::$app->params['baseUrl'] . "verify/{$this->token}",
            //'link' => "",
            'lead_id' => $this->id,
            'partner' => $this->department->partner->name,

        ];
        // Remove pdf untill phone operators approve links in sms
        if ($property) {
            $vars['address'] = $property->adresse;
            $vars['oppdragsnummer'] = $property->oppdragsnummer;
            $vars['pdf'] = Yii::$app->params['baseUrl'] . "salgsoppgave/{$property->oppdragsnummer}.pdf";
        }

        /**
         * Init $smsMap with data to send sms or email
         */
        foreach ($smsMap as $smsReceiver => $sms) {
            //TODO: add to loop all datas

            // Message
            $sms['message'] = $sms['message'] ? $sms['message'] :
                (isset($smsTextsMap[$smsReceiver]) ? $smsTextsMap[$smsReceiver] : false)
            ;

            //Phone
            // ATTANTION: this row is for blocking emails from dev or other local servers. Do NOT comment it. to manage data go to common/config/params-local.php
            $sms['phone'] = ($sms['phone'] ? $sms['phone'] :
                ( isset($defaultSmsMap[$smsReceiver]['phone']) ? $defaultSmsMap[$smsReceiver]['phone'] : false)
            );
            $sms['phone'] = str_replace(' ', '', $sms['phone']);
            $sms['phone'] = strlen($sms['phone']) == 8 ? "+47{$sms['phone']}" : $sms['phone'];

            // Enabled
            $sms['enabled'] = $sms['message'] && $sms['phone'] && $sms['enabled'];

            // Init
            $smsMap[$smsReceiver] = $sms;

        }

        foreach ($smsMap as $receiverType => $sms) {
            if (!$sms['enabled']){ continue; }
            $m = $this->initMessage($sms['message'], $vars);
            $smsSender->publishSms("{$m}","{$sms['phone']}");
        }
    }

    /**
     * @param string $message
     * @param array $vars
     * @return string
     */
    public function initMessage($message, $vars)
    {
        foreach ($vars as $key => $var) {
            $message = str_replace("{{{$key}}}", $var, $message);
        }

        return $message;
    }

    /**
     * Send email.
     *
     * @param User $user
     *
     * @param array $args
     * @return void
     */
    public function sendEmailToBrokerOrDirector($user, $args = []){
        //TODO: rework function
        if (!isset($this->emailSubjects[$this->type])){
            return;
        }
        $emailMap = [
            'broker' => [
                "sender"=>null,
                "user"=>$user,
                "type"=>"broker",
                "to"=>"{$user->navn} <{$user->email}>",
            ],
            'client' => [
                "user"=>$user,
                "sender"=>($this->hasType('salgsoppgave') && $this->user)
                    //TODO: uncomment when partners email services will be approved
                    // ? "=?utf-8?B?{$brokerName}?= <{$this->user->email}>"
                    ? "=?utf-8?B?" . base64_encode($this->user->navn) . "?= <post@partners.no>"
                    : null,
                "type"=>"client",
                "to"=>"{$this->name} <{$this->email}>",
            ],
        ];

        if ($this->target_id && $this->propertyDetails && $this->propertyDetails->user2){
            $emailMap['broker2'] = [
                "sender"=>null,
                "user"=>$this->propertyDetails->user2,
                "type"=>"broker",
                "to"=>"{$this->propertyDetails->user2->navn} <{$this->propertyDetails->user2->email}>",
            ];
        }

        foreach ($emailMap as $data) {
            if (!isset($this->emailSubjects[$this->type][$data['type']])){continue;};
            // try {
                $subject = $this->emailSubjects[$this->type][$data['type']];
                $mailer = new SesMailer;
                $body = Yii::$app->controller->renderPartial("@frontend/views/emails/{$data['type']}/$this->type", [
                    'form' => $this,
                    'user' => $data['user'],
                    'args' => $args
                ]);

                file_put_contents('email_debugg.php',"\n {$this->type}:{$this->name}\n {$body}", FILE_APPEND);

                if ($this->target_id) {
                    $subject = str_replace('{{address}}', $this->propertyDetails->adresse, $subject);
                }
                if(!!Yii::$app->params['enableEmail']) {
                    $response = $mailer->sendMail($body, $subject, [$data['to']], $data['sender']);
                    if ($mailer->fails()) {
                        Yii::error($response);
                    }
                }
            // } catch (\Exception $exception) {
            //     Yii::error($exception->getMessage());
            // }
        }
    }

    /**
     * Return the closest department for 00-14 postcodes and random one for the others
     * @param int $postNumber
     * @return array|Department|null
     */
    public function closestDepartment($postNumber = 0){
        $deps = Department::find()
            ->joinWith('postNumberDetails')
            ->where(['department.inaktiv' => 0])
            ->all()
        ;
        $postPrefix = intval(substr($postNumber, 0, 2));
        $department = false;
        if (
            // May be needed later
                // $postPrefix >= 0 &&
                // $postPrefix <= 14 &&
                // If belongs to Oslo or Akerhuse
            $post = AllPostNumber::findOne(['post_number' => $postNumber])
        ){
            $minRange = INF;
            foreach ($deps as $dep) {
                if (!$dep->postNumberDetails){continue;}
                $d = $this->distance(
                    $dep->postNumberDetails->lat,// φ1
                    $dep->postNumberDetails->lon,// λ1
                    $post->lat,// φ2
                    $post->lon // λ2
                );

                if ($d >= $minRange) {continue;}

                $department = $dep;
                $minRange = $d;
            }
        }
        $department = $department ? $department : $deps[array_rand($deps)];
        return $department;
    }

    /**
     * @param $f1
     * @param $d1
     * @param $f2
     * @param $d2
     * @return float|int
     */
    private function distance($f1, $d1, $f2, $d2)
    {
        /*
         * a = sin²(Δφ/2) + cos φ1 ⋅ cos φ2 ⋅ sin²(Δλ/2)
         * c = 2 ⋅ atan2( √a, √(1−a) )
         * d = R ⋅ c
        */
        $R = 6371 * 1000; // R Earth Radius in meters
        $f1 = deg2rad($f1);// φ1
        $f2 = deg2rad($f2);// φ2
        $d1 = deg2rad($d1);// λ1
        $d2 = deg2rad($d2);// λ2
        $df = sin(($f1 - $f2) / 2);
        $df = $df * $df;// sin²(Δφ/2)

        $dd = sin(($d1 - $d2) / 2);
        $dd = $dd * $dd;// sin²(Δλ/2)
        $a = $df + cos($f1) * cos($f2) * $dd;// sin²(Δφ/2) + cos φ1 ⋅ cos φ2 ⋅ sin²(Δλ/2)
        $c = 2 * atan2(sqrt($a), sqrt(1 - $a));// 2 ⋅ atan2( √a, √(1−a) )

        $L = $R * $c;// R ⋅ c
        return $L;
    }

    /**
     * @return string|null
     */
    public static function generateToken()
    {
        $chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz";
        $size = strlen($chars);
        $token = null;
        for($i = 0; $i < 15; $i++) {
            $token .= $chars[rand(0, $size - 1)];
        }
        return $token;
    }

    /**
     * A lead has the type.
     *
     * @param mixed $type
     *
     * @return bool
     */
    public function hasType($type)
    {
        if (is_array($type)) {
            return in_array($this->type, $type);
        }

        return $this->type === $type;
    }

    /**
     * Determine flag if the hot client.
     *
     * @return bool
     */
    public function isHot()
    {
        return in_array($this->type, self::$hotTypes);
    }

    /**
     * Determine flag if the cold client.
     *
     * @return bool
     */
    public function isCold()
    {
        return in_array($this->type, self::$coldTypes);
    }

    /**
     * Determine flag if the interested client.
     *
     * @return bool
     */
    public function isInterested()
    {
        return in_array($this->type, self::$interestedTypes);
    }

    /**
     * Return list of hot types
     *
     * @return array
     */
    public static function getHotTypes()
    {
        return self::$hotTypes;
    }

    /**
     * Return list of cold types
     *
     * @return array
     */
    public static function getColdTypes()
    {
        return self::$coldTypes;
    }

    /**
     * Return list of iterested types
     *
     * @return array
     */
    public static function getInterestedTypes()
    {
        return self::$interestedTypes;
    }

    /**
     * Determine flag if the hot client.
     *
     * @return bool
     */
    public function justNew()
    {
        return parent::__get('status') == '1001';// TODO: use code of status
    }

    public static function getLeadsCount($id)
    {
        $types = ['salgsoppgave', 'visningliste', 'budvarsel', 'book_visning'];
        $prop = self::find()
            ->select(['type', 'count(type) as count',])
            ->where(['target_id' => $id])
            ->andWhere(['in', 'type', $types])
            ->groupBy(['type'])
            ->asArray()
            ->all();
        $prop = ArrayHelper::map($prop, 'type', 'count');
        foreach ($types as $type) {
            if (!array_key_exists($type, $prop)) {
                $prop[$type] = 0;
            }
        }
        return $prop;
    }

    public function getBrokerName()
    {
        return $this->user->navn ?? null;
    }

    public function getBrokerAvatar()
    {
        return $this->user->urlstandardbilde ?? null;
    }

    public function getDelegatedBrokerName()
    {
        return $this->delegatedUser->navn ?? null;
    }

    public function getDelegatedBrokerAvatar()
    {
        return $this->delegatedUser->urlstandardbilde ?? null;
    }

    public function fields()
    {
        return array_merge(parent::fields(), [
            'brokerName',
            'brokerAvatar',
            'delegatedBrokerName',
            'delegatedBrokerAvatar'
        ]);
    }

    /**
     * Change type of Forms from salgssum_venter to salgssum and send sms to broker and clients,
     * where form.target_id is in $propertyIds
     * @param array $targetIds
     */
    public static function initiateSalgSums($targetIds)
    {
        $forms = Forms::find()
            ->joinWith(['user','propertyDetails'])
            ->where([
                'type' => 'salgssum_venter',
                'target_id' => $targetIds,
            ]);

        $forms = $forms->all();

        /** @var array broker targets map for forms */
        $btm = [];
        /** @var Forms[] $forms */
        foreach ($forms as $form) {
            $form->type = 'salgssum';
            $form->save();
            $key = "{$form->user->web_id}{$form->target_id}";
            if(!isset($btm[$key])){
                $btm[$key] = [
                    'user' => $form->user,
                    'property' => $form->propertyDetails,
                    'forms' => [],
                ];
            }
            $btm[$key]['forms'][] = $form;
        }

        foreach ($btm as $broker) {
            $forms[0]->sendEmailToBrokerOrDirector($broker['user'],$broker);
        }
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPostNumber(){
        return $this->hasOne(AllPostNumber::className(), ['post_number' => 'post_number']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClient(){
        return $this->hasOne(Client::className(), ['id' => 'client_id']);
    }

    /**
     * Determine if the current lead is owned by auth user.
     *
     * @return bool
     */
    public function isOwner()
    {
        return in_array(Yii::$app->user->identity->web_id, [
            $this->broker_id,
            // ...
        ]);
    }

    /**
     * @param $m
     * @throws \Exception
     * TODO: move all slack interactions to single controller
     */
    static private function slackMessage($m){
        if (
            !Yii::$app->params['slackReport']
            || !($room = Yii::$app->params['slackAlarmRoom'])
            || !Forms::mayLogAndSms()
        ){return;}
        $m .= Yii::$app->params['currentBranch'] ? (" (" . Yii::$app->params['currentBranch'] . ")") : " (NOT Ringeliste)";

        $ch = curl_init($room);
        curl_setopt_array($ch, [
            CURLOPT_CUSTOMREQUEST => 'POST',
            CURLOPT_POSTFIELDS => json_encode(['text' => $m,]),
            CURLOPT_HTTPHEADER => ['Content-type: application/json'],
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_SSL_VERIFYPEER => false,
            CURLOPT_TIMEOUT => 5,
        ]);
        $result = curl_exec($ch);
        curl_close($ch);
    }
}
