<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%ledige_stillinger}}".
 *
 * @property int $id
 * @property string $title
 * @property int $kontor
 * @property int $date
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 * @property $department Department
 */
class LedigeStillinger extends ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%ledige_stillinger}}';
    }

    public function beforeSave($insert)
    {
        if($this->date  && !is_int($this->date )) {
            $this->date = strtotime($this->date );
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function showDate() {
        $this->date = strtotime($this->date);
        if($this->date > time()) {
            return date('d.F', $this->date);
        }
        return 'First utløpt';
    }

    public function afterFind()
    {
        if($this->date  && is_int($this->date )) {
            $this->date = date('m/d/Y', $this->date );
        }
        parent::afterFind(); // TODO: Change the autogenerated stub
    }


    public function behaviors()
    {
        return [TimestampBehavior::className()];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['kontor', 'title', 'date'], 'required'],
            [['kontor', 'status', 'created_at', 'updated_at'], 'integer'],
            [['title'], 'string', 'max' => 255],
            [['date'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'title' => Yii::t('app', 'TITTEL'),
            'kontor' => Yii::t('app', 'KONTOR'),
            'date' => Yii::t('app', 'FRIST'),
            'status' => Yii::t('app', 'status'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDepartment() {
        return $this->hasOne(Department::className(), ['id' => 'kontor']);
    }

    /**
     * {@inheritdoc}
     * @return \common\models\activeQuery\LedigeStillingerQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\activeQuery\LedigeStillingerQuery(get_called_class());
    }
}
