<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "process".
 *
 * @property int $id
 * @property int $pid
 * @property int $db_id
 * @property int $createdate
 * @property int $requestdate
 * @property string $type
 */
class Process extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'process';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['pid', 'db_id', 'createdate', 'requestdate'], 'integer'],
            [['type'], 'string', 'max' => 10],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'pid' => 'Pid',
            'db_id' => 'Db ID',
            'createdate' => 'createdate',
            'requestdate' => 'Requestdate',
            'type' => 'Type',
        ];
    }

    /**
     * Check is process still runing on linux or windows separatly from current process
     * @return bool
     */
    public function isParalelProcess(){
        $pid = $this->pid;

        
        if (
            $pid == getmypid() //this object is for current process
            || !isset(Yii::$app->request->isAjax) // process is not console command
        ){return false;}

        $return = false;
        if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {// Windows
            $tl = [];
            exec("tasklist 2>NUL", $tl);
            foreach ($tl as $i=>$r) {
                $r = str_replace(' ', '', $r);
                if (strpos($r, "php.exe{$pid}") !== false){
                    $return = true;
                    break;
                }
            }
        } else {// LINUX
            $return = file_exists( "/proc/$pid" );
        }
        return $return;
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert){
        if ($insert){$this->createdate = time();}
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
