<?php
namespace console\controllers;

use consik\yii2websocket\events\WSClientMessageEvent;
use consik\yii2websocket\WebSocketServer;
use yii\console\Controller;

class ServerController extends Controller
{
    public function beforeAction($action)
    {
        \console\models\SocketServer::runSocked();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionStart()
    {

    }
}