<?php

namespace api\modules\mobile\modules\v1\controllers;


use api\components\ApiResponseHelper;
use api\modules\mobile\modules\v1\exception\UserNotFoundException;
use api\modules\mobile\modules\v1\models\User;
use yii\filters\auth\HttpBearerAuth;
use yii\filters\ContentNegotiator;
use yii\rest\ActiveController;
use yii\web\Response;
use Yii;

/**
 * User controller for the `mobile/v1` module
 */
class UserController extends ActiveController
{

    public $modelClass = User::class;

    public function actions()
    {
        $actions = parent::actions();
        unset($actions["index"]);
        return $actions; // TODO: Change the autogenerated stub
    }


    public function behaviors()
    {
        return [
            'authenticator' => [
                'class' => HttpBearerAuth:: class, // Implementing access token authentication
            ],
            'contentNegotiator' => [
                'class' => ContentNegotiator::class,
                'formatParam' => 'format',
                'formats' => [
                    'json' => Response::FORMAT_JSON,
                ],
            ]
        ];
    }

    /**
     * @return User[]|array
     */
    public function actionList()
    {
        return ApiResponseHelper::responseTemplate(200, [
            "data" => [
                "users" => User::find()->active()->all()
            ]
        ]);
    }


    /**
     * @param $id
     * @return array
     */
    public function actionInfo($id)
    {
        return $this->findModel($id);
    }

    /**
     * @param $id
     * @return array
     */
    protected function findModel($id)
    {
        $user = User::find()->where(["id" => $id])->active()->one();

        return $user ? ApiResponseHelper::responseTemplate(200, ["data" => ["user" => $user]])
            : ApiResponseHelper::responseTemplate(404,
                ["error" => ["message" => "User not found"]]);

    }

}
